spring:
  application:
    name: accounts-microservice
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 3333
  error:
    whitelabel:
      enabled: true